### PR TITLE
Add https port definition

### PR DESCRIPTION
**Pull request by blaggacao**
Atop #205 

That keeps downstream kustomization files a little cleaner.

Maybe there are ways to also add it to the two ingress controllers
(as convenience defaults) without breaking anything?

if this is at risk of causing any troubles, better let's drop it.

<sub>a series of perceived tiny improvements from while working on #193</sub>

### CODE REVIEW

**Comment by amouat** [comment]
Yes, this probably makes sense.

I've been meaning to go through the install and make it use TLS between ingress and Trow, which isn't the case by default atm.

**Comment by blaggacao** [comment]
> I've been meaning to go through the install and make it use TLS between ingress and Trow, which isn't the case by default atm.

Wanting to use spiffe for that, I got stuck with current lack of ECDSA cert support.

**Comment by blaggacao** [comment]
So I rebased (8000 / 8443) to not to induce any not-yet-vested implications. I'm happy to hold this in stock or close as for when you'd want to make progress on this topic.

**Comment by amouat** [comment]
@blaggacao could you resolve the conflicts and I'll merge this?

**Comment by blaggacao** [comment]
@amouat Done. Thank you!

**Review by amouat — APPROVED** [review]

**Pull request merged**
