### PR TITLE
Added 3 level paths and added a test. Fixed -d flag.

### PR DESCRIPTION
**Pull request by ztulloch**

### CODE REVIEW

**Comment by amouat** [comment]
This looks good! It definitely doesn't matter for this, but normally it would probably be best to have the `-d` fix in a different PR.

**Comment by hamhut1066** [comment]
Thanks for the changes, I left some feedback on the PR

**Comment by amouat** [comment]
Thanks Hamish! Yeah, good point about "?" and the printlns. Zander, I think you can just push an update to the branch for this PR, then I think it's pretty much good to go.

**Comment by ztulloch** [comment]
Thanks for the feedback Hamish! I'll sort those out.

**Comment by amouat** [comment]
Removed unwraps and merged. We still need to take care of testing getting manifests with different levels (name vs user/name vs org/user/name) and refactoring.

**Pull request merged**
