### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by awoimbee**
Small PR to update the dependencies and to remove the old `external crate` syntax.
I also fixed the 2-3 clippy errors (it wasn't much).
Thanks for maintaining this project !

### CODE REVIEW

**Comment by amouat** [comment]
Thanks! I didn't know about the extern crate change :)

**Comment by amouat** [comment]
There's something weird happening with this - the tests don't seem to run. If you have time, just try running `cargo test` on your repo. Otherwise I'll look into it later.

**Comment by amouat** [comment]
Yeah, something has changed in the CLI tests. It's hanging on test cli::log_level_setting

**Comment by awoimbee** [comment]
Sorry for that, seems like I partly fixed `log_level_setting` by adding `.unwrap()` but it broke everything because of a missing `--dry-run`. It should be good now !

---

Small question: how to run the following tests ?
```
tests/authentication.rs
tests/cors.rs
tests/manifest_history.rs
tests/proxy.rs
tests/registry_interface.rs
tests/size_tests.rs
tests/validation_interface.rs
```
When I run them, Trow opens and that's it, I can only `ctrl+c`, which cancels all the tests (I'm stuck on `Trow is up and running!`).

**Comment by amouat** [comment]
Hmm, the tests should run. I'll take a look.

**Comment by awoimbee** [comment]
Should be all good, I ran the CI locally using https://github.com/nektos/act. I didn't manage to make it go all the way (assertion failed at `tests/smoke-test.rs:106:9`) but I was able to do the test manually without any problem:
```bash
cargo run -- --no-tls --proxy-docker-hub --allow-docker-official --allow-prefixes docker.io --port 9999 &
docker pull alpine:latest
docker tag alpine:latest 127.0.0.1:9999/alpine:latest
docker push 127.0.0.1:9999/alpine:latest
docker rmi 127.0.0.1:9999/alpine:latest
docker pull 127.0.0.1:9999/alpine:latest
```
I hope this time is the right one !

**Comment by amouat** [comment]
LGTM! Thanks for this.

**Pull request merged**
