### PR TITLE
Update default.nix to allow nix-shell to function again

### PR DESCRIPTION
**Pull request by imacg**
* Update Mozilla nix overlay to current master
* Synchronize Rust nightly date with docker/Dockerfile.*
* Pass path of protoc to trow-protobuf build script via PROTOC envvar

### CODE REVIEW

**Review by amouat — APPROVED** [review]

**Comment by amouat** [comment]
Wow. This is awesome, thanks. I was actually going to delete `default.nix` as I didn't think anyone used it anymore (@moredhel wrote it originally).

Let me figure out why this test is failing and I'll merge (I don't see how the test can have anything to do with your change so it's a bit weird).

**Comment by imacg** [comment]
@amouat glad to help. I am by no means a Nix expert, but I really like it's approach to reproducible build environments. If there is an appetite for it I'd could work on some further improvements (eg. pinning `nixpkgs`, making the scripts in the repo work on NixOS, etc).

**Comment by moredhel** [comment]
Thanks Ian for the contribution! 


--

/moredhel

**Comment by amouat** [comment]
@imacg feel free to contribute anything you like to the nix stuff!

Unfortunately I don't really use it myself and I'm unsure who else is using it, but it's certainly a nice thing to have.

**Pull request merged**
