### PR TITLE
Use named ports

### PR DESCRIPTION
**Pull request by blaggacao**
Named ports helps with better reasoning over the service's port
abstractions.

<sub>a series of perceived tiny improvements from while working on #193</sub>

### CODE REVIEW

**Comment by amouat** [comment]
Yes, definitely a good idea, but I'm a bit concerned with changing the service port to `80` from `8000`. I'm trying to figure out when that port is used and I'm not sure. It would be used for internal k8s communication, so may affect the health check for example.

**Comment by blaggacao** [comment]
The service port 80 (or 443) is only used when the service is accessed directly. That only is the cade for a cluster wide ingress controller (since containerd/ etc) are not plugged into the k8s dns when pulling images. So any "in cluster" fetching would have to go through node port anyway (localhost:<nodeport>).

In order not to (implicitly) insinuate it's relevant we probably should leave it at 8000. I'll fixup.

**Comment by amouat** [comment]
Yeah, it can't affect the health check as that must be implemented at the container level (I think even below the pod level).

It probably depends on the ingress controller - I think most of them try to avoid the overhead of going through the service and enumerate the pods directly (at least that's what the nginx ingress used to do).

**Comment by blaggacao** [comment]
So I forced pushed and reverted back to 8000 to avoid any tacit [not-yet-vested](https://github.com/ContainerSolutions/trow/issues/211) implications.

**Comment by amouat** [comment]
I'm about to merge this.

In general the installers need more testing with various platforms. We may be able to extend the existing Helm tests with microk8s to cover some cases, but others need tests with specific platforms e.g. GKE which is more difficult to automate.

**Review by amouat — APPROVED** [review]

**Pull request merged**
